Spanish translation (text.js)
Caldis/Mos pull request #527
Opened 2022-10-03 18:26 UTC by kant

2024-07-23 18:10 UTC, jfrsa requested changes

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "MOS | Легкий инструмент, используемый для плавной прокрутки и установки направления прокрутки независимо для вашей мыши на MacOS"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Легкий инструмент, используемый для плавной прокрутки и установки независимого направления прокрутки для вашей мыши на MacOS"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Полный контроль над мышью"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Mos разделяет прокрутку тачпада и мыши, вы можете установить направление прокрутки сенсорной панели и колесика мыши отдельно. Кроме того, Mos обеспечивает плавную прокрутку для вашей
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Максимальная плавность"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Специальный алгоритм интерполяции Mos может сделать любую мышку более гладкой и шелковистой."
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Каждая программа под контролем"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Mos может самостоятельно управлять поведением прокрутки каждого приложения."
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Так чего же вы ждете?"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Создано и разработано "
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: ", и всеми"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "разработчиками"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "и"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "участниками сообщества"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Работает на "
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Посвящается каждому пользователю MacOS"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Скачать сейчас"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Скачать сейчас"
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: "Версия "
Missing comma at the end

2024-07-23 18:10 UTC, jfrsa commented on docs/src/i18n/text.js
>              ru: ", требуется macOS 10.11 или более поздняя версия"
Missing comma at the end

2025-01-10 09:43 UTC, merged

2025-01-10 09:43 UTC, Caldis commented
@kant @jfrsa Thank you for your contribution !